// GENERATED by scripts/gen-programs.mjs from packages/meridian-contracts/fixtures/revenue-stream/registry.json
// (registry version 1, 16 streams). Do not edit by hand; edit the registry and regenerate.
// Rules carried over from the registry: streams are never summed, and monthly or hourly rates are never
// multiplied into a season or a year. Each rate keeps the unit and period the program document states.
export type Program = "Oncor" | "CenterPoint" | "AEP Texas" | "TNMP" | "ERCOT" | "LADWP" | "CAISO";
export type Stream = {
  rate: [number, number];                              // low–high as published; equal when a single rate
  unit: string;                                        // the published unit, e.g. "per MW a year"
  scale: "mw" | "kw" | "rate";                         // how a site's flexible MW applies: × MW, × MW × 1000, or not at all (show the rate)
  name: string; short?: string; status: string; year?: string;
  cite: { file: string; url: string; retrieved: string };
};
export type ProgramRates = { a: Stream | null; b: Stream | null; priced: boolean; model: boolean; note: string };
export const PROGRAMS: Record<Program, ProgramRates> = {
  "Oncor": {
    "a": {
      "rate": [
        41901,
        41901
      ],
      "unit": "per MW a year",
      "scale": "mw",
      "name": "4CP avoided transmission charge — Oncor",
      "status": "published_2026",
      "year": "2026",
      "cite": {
        "file": "firm_cost.csv",
        "url": "https://ftp.puc.texas.gov/public/puct-info/industry/electric/rates/tdr/tdu/Oncor_Rate_Report.pdf",
        "retrieved": "2026-08-29"
      }
    },
    "b": {
      "rate": [
        0.4992,
        8.6856
      ],
      "unit": "per MW-hour committed",
      "scale": "rate",
      "short": "ERS or reserves",
      "name": "ERS or reserves (ECRS / RRS / NSRS), 2025–2026",
      "status": "published_2025, estimate_2026",
      "cite": {
        "file": "dr_ers_procurement.csv",
        "url": "https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1188179018",
        "retrieved": "2026-08-29"
      }
    },
    "priced": true,
    "model": true,
    "note": "Oncor 4CP, PUCT rate report 2026 · ERS and reserves as cleared, 2025–2026"
  },
  "CenterPoint": {
    "a": {
      "rate": [
        75270,
        75270
      ],
      "unit": "per MW a year",
      "scale": "mw",
      "name": "4CP avoided transmission charge — CenterPoint",
      "status": "published_2026",
      "year": "2026",
      "cite": {
        "file": "firm_cost.csv",
        "url": "https://ftp.puc.texas.gov/public/puct-info/industry/electric/rates/tdr/tdu/Oncor_Rate_Report.pdf",
        "retrieved": "2026-08-29"
      }
    },
    "b": {
      "rate": [
        0.4992,
        8.6856
      ],
      "unit": "per MW-hour committed",
      "scale": "rate",
      "short": "ERS or reserves",
      "name": "ERS or reserves (ECRS / RRS / NSRS), 2025–2026",
      "status": "published_2025, estimate_2026",
      "cite": {
        "file": "dr_ers_procurement.csv",
        "url": "https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1188179018",
        "retrieved": "2026-08-29"
      }
    },
    "priced": true,
    "model": true,
    "note": "CenterPoint 4CP, PUCT rate report 2026 · ERS and reserves as cleared, 2025–2026"
  },
  "AEP Texas": {
    "a": {
      "rate": [
        71640,
        71640
      ],
      "unit": "per MW a year",
      "scale": "mw",
      "name": "4CP avoided transmission charge — AEP Texas North",
      "status": "published_2026",
      "year": "2026",
      "cite": {
        "file": "firm_cost.csv",
        "url": "https://ftp.puc.texas.gov/public/puct-info/industry/electric/rates/tdr/tdu/Oncor_Rate_Report.pdf",
        "retrieved": "2026-08-29"
      }
    },
    "b": {
      "rate": [
        0.4992,
        8.6856
      ],
      "unit": "per MW-hour committed",
      "scale": "rate",
      "short": "ERS or reserves",
      "name": "ERS or reserves (ECRS / RRS / NSRS), 2025–2026",
      "status": "published_2025, estimate_2026",
      "cite": {
        "file": "dr_ers_procurement.csv",
        "url": "https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1188179018",
        "retrieved": "2026-08-29"
      }
    },
    "priced": true,
    "model": true,
    "note": "AEP Texas 4CP, PUCT rate report 2026 · ERS and reserves as cleared, 2025–2026"
  },
  "TNMP": {
    "a": {
      "rate": [
        38183,
        38183
      ],
      "unit": "per MW a year",
      "scale": "mw",
      "name": "4CP avoided transmission charge — TNMP",
      "status": "published_2026",
      "year": "2026",
      "cite": {
        "file": "firm_cost.csv",
        "url": "https://ftp.puc.texas.gov/public/puct-info/industry/electric/rates/tdr/tdu/Oncor_Rate_Report.pdf",
        "retrieved": "2026-08-29"
      }
    },
    "b": {
      "rate": [
        0.4992,
        8.6856
      ],
      "unit": "per MW-hour committed",
      "scale": "rate",
      "short": "ERS or reserves",
      "name": "ERS or reserves (ECRS / RRS / NSRS), 2025–2026",
      "status": "published_2025, estimate_2026",
      "cite": {
        "file": "dr_ers_procurement.csv",
        "url": "https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1188179018",
        "retrieved": "2026-08-29"
      }
    },
    "priced": true,
    "model": true,
    "note": "TNMP 4CP, PUCT rate report 2026 · ERS and reserves as cleared, 2025–2026"
  },
  "ERCOT": {
    "a": {
      "rate": [
        38183,
        75270
      ],
      "unit": "per MW a year",
      "scale": "mw",
      "name": "4CP avoided transmission charge, TNMP to CenterPoint",
      "status": "published_2026",
      "year": "2026",
      "cite": {
        "file": "firm_cost.csv",
        "url": "https://ftp.puc.texas.gov/public/puct-info/industry/electric/rates/tdr/tdu/Oncor_Rate_Report.pdf",
        "retrieved": "2026-08-29"
      }
    },
    "b": {
      "rate": [
        0.4992,
        8.6856
      ],
      "unit": "per MW-hour committed",
      "scale": "rate",
      "short": "ERS or reserves",
      "name": "ERS or reserves (ECRS / RRS / NSRS), 2025–2026",
      "status": "published_2025, estimate_2026",
      "cite": {
        "file": "dr_ers_procurement.csv",
        "url": "https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1188179018",
        "retrieved": "2026-08-29"
      }
    },
    "priced": true,
    "model": true,
    "note": "4CP across the four Texas utilities, PUCT rate reports 2026 · ERS and reserves as cleared, 2025–2026"
  },
  "LADWP": {
    "a": {
      "rate": [
        10,
        15
      ],
      "unit": "per kW a month of the season",
      "scale": "kw",
      "name": "LADWP demand response capacity incentive, day-ahead to two-hour notice",
      "status": "verified_2025_tc",
      "year": "2025",
      "cite": {
        "file": "flexuw/ladwp/config.py",
        "url": "https://www.ladwp.com/sites/default/files/2025-06/Terms%20and%20Conditions%20-%20LADWP%20Demand%20Response%20CI%20Program.pdf",
        "retrieved": "2026-09-02"
      }
    },
    "b": {
      "rate": [
        0.25,
        0.25
      ],
      "unit": "per kWh delivered in events",
      "scale": "rate",
      "short": "event energy",
      "name": "LADWP C&I demand response event energy payment",
      "status": "verified_2025_tc",
      "cite": {
        "file": "flexuw/ladwp/config.py",
        "url": "https://www.ladwp.com/sites/default/files/2025-06/Terms%20and%20Conditions%20-%20LADWP%20Demand%20Response%20CI%20Program.pdf",
        "retrieved": "2026-09-02"
      }
    },
    "priced": true,
    "model": false,
    "note": "LADWP capacity incentive, $10 to $15 per kW a month, June 15 to October 15, 2025 terms. Event energy is additional."
  },
  "CAISO": {
    "a": null,
    "b": null,
    "priced": false,
    "model": false,
    "note": "Not priced yet: no program source on file for California outside Los Angeles."
  }
};
// The share of a campus Meridian designs as flexible in the illustrative campus above (40 of 96 MW).
// An illustration, not a facility result: a real site's share comes from its own assessment.
export const FLEX_SHARE = 0.4;
export const money = (v: number) => v >= 1e6 ? `$${(v / 1e6).toFixed(1)}M` : v >= 1e3 ? `$${Math.round(v / 1e3)}k` : v >= 100 ? `$${Math.round(v)}` : `$${v.toFixed(2)}`;
export const range = (lo: number, hi: number) => lo === hi ? money(lo) : `${money(lo)} – ${money(hi)}`;
// A stream applied to a site's flexible MW, in the stream's own period: a value and the words after it.
export const applied = (s: Stream, mw: number): { text: string; after: string } => {
  if (s.scale === "mw") return { text: range(s.rate[0] * mw, s.rate[1] * mw), after: "a year" };
  if (s.scale === "kw") return { text: range(s.rate[0] * mw * 1000, s.rate[1] * mw * 1000), after: "a month of the season" };
  return { text: range(s.rate[0], s.rate[1]), after: s.unit };
};
